In [1]:
import numpy as np

In [3]:
arr = np.arange(5)

In [4]:
arr

array([0, 1, 2, 3, 4])

In [5]:
np.save('myarray',arr)

In [6]:
arr = np.arange(10)

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr1 = np.load('myarray.npy')

In [10]:
arr2 = arr

In [17]:
np.savez('ziparray.npz', x = arr1, y = arr2)

In [18]:
arch = np.load('ziparray.npz')

In [19]:
arch

In [21]:
arch['x']

array([0, 1, 2, 3, 4])