In [17]:
import numpy as np


In [18]:
my_list1 = [1,2,3,4]

In [19]:
my_array1 = np.array(my_list1)

In [20]:
my_array1

array([1, 2, 3, 4])

In [21]:
my_list2 = [11,22,33,44]

In [22]:
my_lists = [my_list1,my_list2]


In [23]:
my_array2 = np.array(my_lists)

In [24]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [25]:
my_array2.shape

(2, 4)

In [26]:
my_array2.dtype

dtype('int64')

In [27]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [28]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [29]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [30]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

Some Lecture 8 notes as well

In [31]:
from __future__ import division

In [32]:
5/2

2.5

In [35]:
import numpy as np

In [38]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [39]:
arr1


array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [40]:
arr1-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [41]:
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])